name       : stfl
version    : 0.24
release    : 2
source     :
    - http://www.clifford.at/stfl/stfl-0.24.tar.gz : d4a7aa181a475aaf8a8914a8ccb2a7ff28919d4c8c0f8a061e17a0c36869c090
license    : GPL-3.0
component  : programming
summary    : Structured Terminal Forms Language/Library
description: |
    STFL is a library that implements a curses-based widget set for text terminals. The STFL API can be used from C, SPL, Python, Perl, and Ruby. The API contains only 14 simple function calls and there are SWIG bindings for helping to port STFL to other scripting languages.
build      : |
    %make
install    : |
    %make_install prefix=/usr libdir=lib64
    rm -f $installdir/usr/lib64/*.a
    ln -s libstfl.so.0.24 $installdir/%libdir%/libstfl.so.0
